on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Import Vault dev secrets"
        uses: hashicorp/vault-action@v2.2.0
        id: secrets
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          exportEnv: false # <-- This is the important setting to avoid unnecessary credential exposure!
          secrets: |
            secret/dsde/dev/appsec/gh-test foo | CREDENTIALS_SECRET ;
      - name: "Test env" # <-- This step uses the secret as an "output" of Vault Action step, instead of global environment variables (which would increase the risk)
        run: |
          echo '$CREDENTIALS_SECRET:' $CREDENTIALS_SECRET # this will be empty, since the secret is no longer passed via a global environment variable
          echo '${ steps.secrets.outputs.CREDENTIALS_SECRET }:' ${{ steps.secrets.outputs.CREDENTIALS_SECRET }} # this will be masked in log outputs
